name: AdminUtils
version: 1.0.0
author: SciDev
api-version: 1.16
main: me.scidev.adminUtils.AdminUtils
commands:
   invsee:
      description: See another players inventory.
      permission: adminutils.commands.invsee.use
      aliases: ["inv"]
      usage: "/<command> <player>"
   freeze:
      description: Freeze a player in place.
      permission: adminutils.commands.freeze.use
      usage: "/<command> <player>"
   unfreeze:
      description: Unfreeze a frozen player.
      permission: adminutils.commands.unfreeze.use
      usage: "/<command> <player>"
   ban:
      description: Ban a player from the server.
      permission: adminutils.commands.ban.use
      usage: "/<command> <player> [duration] [reason... ]"
   ban-ip:
      description: Ban a player from the server by their ip.
      permission: adminutils.commands.ban.use
      usage: "/<command> <player> [duration] [reason... ]"
   kick:
      description: Kick a player from the server.
      permission: adminutils.commands.kick.use
      usage: "/<command> <player> [reason... ]"
   pardon:
      description: Unban a player from the server.
      permission: adminutils.commands.pardon.use
      usage: "/<command> <player>"
   pardon-ip:
      description: Un ip-ban a player from the server.
      permission: adminutils.commands.pardon.use
      usage: "/<command> <ip>"
   warn:
      description: Warn a player for doing something wrong.
      permission: adminutils.commands.warn.use
      usage: "/<command> <player> <reason... >"
